### ISSUE TITLE
Share code to update the list more frequently 

### ISSUE THREAD

**Issue by kx499** [ejrv/VPNs#2]
I was wondering if you would be able to share the code you use to update these lists, I'd like to be able to update more frequently. PIA for example adds new servers pretty regularly and I'd like to nab as much as I can.

**Comment by m-cameron** [comment]
Do you have any suggestion where to get the PIA server lists?

**Comment by kx499** [comment]
OpenVPN configs would be the best bet. https://www.privateinternetaccess.com/openvpn/openvpn.zip

**Comment by ejrv** [comment]
I wish :)

Unfortunately, there's no code involved. The hostnames are manually scraped off the URL preceding the IPs in hostname.txt. So for PIA, that involves going to https://www.privateinternetaccess.com/pages/network/ (see line #10014 on hostname.txt).

I grab the HTML and then parse it by hand in a text editor, using a lot of regex, until I'm left with only the hostnames listed on that page. The updates are relatively infrequent because it's a painful manual process that's slightly different for every VPN provider. In future, I may automate it more.

If you're fluent in regex, I'd encourage you to make pull requests with more frequent hostname updates. I'd like to automate a lot more of the work that goes into maintaining this list at some point, but at the moment it's really all just manual regex and a bash script that runs 'dig' on hostname.txt entries.

**Comment by rockcavera** [comment]
Even though it is closed, I will speak here, because it is pertinent.

It would be interesting for the author to automate the creation of the list or make available the places where he collects the IPs for the community to help automate.

I believe that there are several people interested in helping with this.
