### ISSUE TITLE
False Positive: 166.171.56.0/22 is AT&T Mobile

### ISSUE THREAD

**Issue by Wingysam** [ejrv/VPNs#7]
The 166.171.56.0/22 range is owned by AT&T and is used by people without a VPN.

**Comment by ejrv** [comment]
Intentional inclusion, see this blog post for the reasoning behind it: https://krebsonsecurity.com/tag/wireless-data-service-provider-corporation/

166.171.56.0/22 is one of the IPs described in the article and not used by legit AT&T customers. Do let me know if you see actual real-world false positives, but they shouldn't happen.
